apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: dbnamespaces.cluster.odoo.io
spec:
  group: cluster.odoo.io
  names:
    kind: DBNamespace
    plural: dbnamespaces
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            dbAdmin:
              properties:
                password:
                  type: string
                user:
                  type: string
              required:
              - user
              - password
              type: object
            host:
              type: string
            password:
              type: string
            port:
              type: string
            user:
              type: string
            userQuota:
              type: object
          required:
          - host
          - port
          - user
          - password
          - dbAdmin
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            usedQuota:
              type: object
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
