apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: odootracks.cluster.odoo.io
spec:
  group: cluster.odoo.io
  names:
    kind: OdooTrack
    plural: odootracks
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            config:
              type: object
            track:
              type: string
          required:
          - track
          type: object
        status:
          properties:
            currenthead:
              properties:
                apiVersion:
                  type: string
                kind:
                  type: string
                metadata:
                  type: object
                spec:
                  properties:
                    bugfix:
                      type: boolean
                    cluster:
                      type: string
                    config:
                      type: object
                    track:
                      type: string
                    version:
                      type: string
                  required:
                  - version
                  - track
                  - cluster
                  type: object
                status:
                  properties:
                    conditions:
                      items:
                        properties:
                          type:
                            type: string
                        required:
                        - type
                        type: object
                      type: array
                  type: object
              type: object
          required:
          - currenthead
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
