apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: odooclusters.cluster.odoo.io
spec:
  group: cluster.odoo.io
  names:
    kind: OdooCluster
    plural: odooclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            appsecret:
              type: string
            config:
              type: object
            database:
              properties:
                dbAdmin:
                  properties:
                    host:
                      type: string
                    password:
                      type: string
                    port:
                      type: string
                    user:
                      type: string
                  required:
                  - host
                  - port
                  - user
                  - password
                  type: object
                password:
                  type: string
                user:
                  type: string
                userQuota:
                  type: object
              required:
              - user
              - password
              - dbAdmin
              type: object
            image:
              properties:
                registry:
                  type: string
                repo:
                  type: string
                secret:
                  type: string
              required:
              - registry
              - repo
              type: object
            nodes:
              type: object
            resources:
              properties:
                tiers:
                  items:
                    properties:
                      name:
                        type: string
                      qos:
                        type: string
                      replicas:
                        format: int32
                        type: integer
                      resources:
                        type: object
                    required:
                    - name
                    type: object
                  type: array
                volumes:
                  items:
                    properties:
                      name:
                        type: string
                      pvcspec:
                        type: object
                    required:
                    - name
                    - pvcspec
                    type: object
                  type: array
              type: object
            tracks:
              items:
                properties:
                  config:
                    type: object
                  name:
                    type: string
                required:
                - name
                type: object
              type: array
          required:
          - tracks
          - image
          - database
          - config
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
