apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: odooclusters.cluster.odoo.io
spec:
  group: cluster.odoo.io
  names:
    kind: OdooCluster
    plural: odooclusters
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            appsecret:
              type: string
            config:
              type: object
            database:
              properties:
                dbAdmin:
                  properties:
                    host:
                      type: string
                    password:
                      type: string
                    port:
                      format: int64
                      type: integer
                    user:
                      type: string
                  required:
                  - host
                  - port
                  - user
                  - password
                  type: object
                password:
                  type: string
                user:
                  type: string
                userQuota:
                  type: object
              required:
              - user
              - password
              - dbAdmin
              type: object
            image:
              properties:
                registry:
                  type: string
                repo:
                  type: string
                secret:
                  type: string
              required:
              - registry
              - repo
              type: object
            nodes:
              type: object
            resources:
              properties:
                tiers:
                  items:
                    properties:
                      name:
                        type: string
                      qos:
                        type: string
                      replicas:
                        format: int32
                        type: integer
                      resources:
                        type: object
                    required:
                    - name
                    type: object
                  type: array
                volumes:
                  items:
                    properties:
                      name:
                        type: string
                      pvcspec:
                        type: object
                    required:
                    - name
                    - pvcspec
                    type: object
                  type: array
              type: object
            tracks:
              items:
                properties:
                  config:
                    type: object
                  track:
                    type: string
                required:
                - track
                type: object
              type: array
          required:
          - tracks
          - image
          - database
          - config
          type: object
        status:
          properties:
            conditions:
              description: +patchMergeKey=type +patchStrategy=merge
              items:
                properties:
                  type:
                    description: Type of the OdooClusterStatus condition.
                    type: string
                required:
                - type
                type: object
              type: array
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
