apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: odooclusters.cluster.odoo.io
spec:
  group: cluster.odoo.io
  names:
    kind: OdooCluster
    plural: odooclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            adminPassword:
              type: string
            config:
              type: string
            customConfig:
              type: string
            dbNamespaceSpec:
              properties:
                dbAdmin:
                  properties:
                    password:
                      type: string
                    user:
                      type: string
                  required:
                  - user
                  - password
                  type: object
                host:
                  type: string
                password:
                  type: string
                port:
                  type: string
                user:
                  type: string
                userQuota:
                  type: object
              required:
              - host
              - port
              - user
              - password
              - dbAdmin
              type: object
            integratorConfig:
              type: string
            nodeSelector:
              type: object
            resourceQuotaSpec:
              type: object
            tiers:
              items:
                properties:
                  dbConn:
                    format: int32
                    type: integer
                  name:
                    type: string
                  qos:
                    type: string
                  replicas:
                    format: int32
                    type: integer
                  resources:
                    type: object
                required:
                - name
                type: object
              type: array
            tracks:
              items:
                properties:
                  config:
                    type: string
                  customConfig:
                    type: string
                  image:
                    properties:
                      image:
                        type: string
                      registry:
                        type: string
                      secret:
                        type: string
                      tag:
                        type: string
                    required:
                    - registry
                    - image
                    - tag
                    type: object
                  integratorConfig:
                    type: string
                  name:
                    type: string
                required:
                - name
                - image
                type: object
              type: array
            volumes:
              items:
                properties:
                  name:
                    type: string
                  spec:
                    type: object
                required:
                - name
                - spec
                type: object
              type: array
          required:
          - tracks
          - tiers
          - dbNamespaceSpec
          - adminPassword
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
