apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: odooinstances.instance.odoo.io
spec:
  group: instance.odoo.io
  names:
    kind: OdooInstance
    plural: odooinstances
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            cluster:
              type: string
            demo:
              type: boolean
            hostname:
              description: The host name of this instance (mutable)
              type: string
            initModules:
              items:
                type: string
              type: array
            initSQL:
              type: string
            parentHostname:
              type: string
            version:
              description: The version of this instance (immutable) Either Version
                or ParentHostname is required
              type: string
          required:
          - cluster
          - hostname
          type: object
        status:
          properties:
            conditions:
              description: Current service state of apiService. +patchMergeKey=type
                +patchStrategy=merge
              items:
                properties:
                  type:
                    description: Type of the OdooInstanceStatus condition.
                    type: string
                required:
                - type
                type: object
              type: array
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
