apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: odooinstances.instance.odoo.io
spec:
  group: instance.odoo.io
  names:
    kind: OdooInstance
    plural: odooinstances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            dbQuota:
              format: int32
              type: integer
            dbSeedCfgMap:
              type: string
            fsQuota:
              format: int32
              type: integer
            hostname:
              type: string
            modules:
              items:
                type: string
              type: array
            parent:
              type: string
            version:
              type: string
          required:
          - hostname
          - version
          - parent
          - modules
          - demo
          - dbSeedCfgMap
          - dbQuota
          - fsQuota
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            usedDbQuota:
              format: int32
              type: integer
            usedFsQuota:
              format: int32
              type: integer
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
