apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: backups.instance.odoo.io
spec:
  group: instance.odoo.io
  names:
    kind: Backup
    plural: backups
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            backupStrategy:
              properties:
                name:
                  type: string
                storageTarget:
                  type: string
              required:
              - name
              - storageTarget
              type: object
            backupTarget:
              type: string
            odooInstance:
              type: string
          required:
          - odooInstance
          - backupStrategy
          - backupTarget
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
