apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: odooinstances.instance.odoo.io
spec:
  group: instance.odoo.io
  names:
    kind: OdooInstance
    plural: odooinstances
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            demo:
              type: boolean
            hostname:
              type: string
            initModules:
              items:
                type: string
              type: array
            initSQL:
              type: string
            parentHostname:
              type: string
            version:
              type: string
          required:
          - hostname
          - version
          - parentHostname
          - demo
          - initModules
          - initSQL
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
