apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: "null"
  name: database
  namespace: odoo
spec:
  # Adapt this to your database connection
  externalName: your.externa.db.com
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  sessionAffinity: None
  type: ExternalName