apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: odooinstances.odoo.k8s.io
spec:
  group: odoo.k8s.io
  names:
    kind: OdooInstance
    listKind: OdooInstanceList
    plural: odooinstances
    singular: odooinstance
  scope: Namespaced
  version: v1alpha1
