apiVersion: cluster.odoo.io/v1beta1
kind: OdooCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: odoocluster-sample
spec:
  appsecret: app-secret-name

  config:
    options: # Translates to INI section [options]
      db_password: "odoo-operator-password"
      db_user: "odoo-operator-user"

  database:
    dbAdmin:  # Admin access to an external DB cluster
      host: "example.com"
      password: "postgres"
      port: "5432"
      user: "postgres"
    password: "odoo-operator-password"
    user: "odoo-operator-user"

  image:
    registry: "registry.gitlab.com"
    repo: "xoe-labs/odoo-xoe"
    secret: "pull-secret"

  tracks:
  - name: "11.0"
  - name: "12.0"
  - config:
      options:
        without_demo: "false"
    name: "master"

  resources:
    tiers:
    - name: cron
      replicas: 2
      qos: ...
    - name: longpolling
      replicas: 1
      qos: ...
    - name: web
      replicas: 4
      qos: ...
    volumes:
    - name: data
      pvcspec: ...
    - name: backup
      pvcspec: ...

  nodes: ...
