apiVersion: cluster.odoo.io/v1beta1
kind: OdooCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: odoocluster-sample
spec:
  # config: |  # < those will be mapped to the [options] section (cluster-scoped)
  #   db_name = false
  #   db_template = template0
  #   list_db = false
  #   dbfilter = "^%h$"
  #   email_from: ""
  #   smtp_server: ""
  #   smtp_port: "465"
  #   smtp_ssl: "true"
  #   smtp_user: ""
  #   smtp_password: ""
  # integratorConfig: |  # < if you use the [integrator] section (cluster-scoped)
  #   integrator_warranty_url = "https://erp.xoe.solutions/integrator-warranty/"
  # customConfig: |  # < if you use any custom sections (cluster-scoped)
  #   [mysection]
  #   my-key=my-value
  tracks:
    - name: "10.0"  # < eg. 10.0 | 11.0 | 12.0 or 11.0-1.4.3, if you manage sub version release cycles. You can manage several tracks in parallel, see Ingress Controller.
      image:
        # Create registry credentials
        # See: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-in-the-cluster-that-holds-your-authorization-token
        secret: regcred  # < Configure, if this is a private image in a private registry
        registry: "registry.gitlab.com"
        image: "xoe-labs/odoo/odoo-xoe"
        tag: "master"
      # config: |  # < those will be mapped to the [options] section (track-scoped)
      #   log_handler = ":WARNING"
      #   server_wide_modules = web_kanban,web
      # integratorConfig: |  # < if you use the [integrator] section (track-scoped)
      #   integrator_warranty_url = "https://erp.xoe.solutions/integrator-warranty/"
      # customConfig: |  # < if you use any custom sections (track-scoped)
      #   [mysection]
      #   my-key=my-value

    # - name: "11.0"
    #   image:
    #     registry: "registry.gitlab.com"
    #     name: "xoe/odoo/odoo-xoe"
    #     tag: "11.0"
  tiers:
    - name: "Server"
      replicas: 1  # < Scale workers. 1 replica = 1 worker
      # dbConn:  # < Adjust according to expected concurrent workload for normal use, default: 16
      # qos:  # < K8S QOS spec to prioritize resource allocation
      # resources:  # < K8S Resource request: specify available resources per replica
    - name: "Cron"
      replicas: 1
      # qos:  # < K8S QOS spec to prioritize resource allocation
      # resources:  # < K8S Resource request: specify available resources per replica
    - name: "LongPolling"
      replicas: 1
      # dbConn:  # < Adjust according to expected concurrent workload for chat use, default: 16
      # qos:  # < K8S QOS spec to prioritize resource allocation
      # resources:  # < K8S Resource request: specify available resources per replica
  volumes:
    - name: "Data"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      # storageClassName:  # < Use for dynamic provisioning
    - name: "Backup"  # < This is not officially used by Odoo, but custom implementation of some backup cron is so basic to reliable operation, it landed here.
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
      # storageClassName:  # < Use for dynamic provisioning

  dbNamespaceSpec:  # < TODO: Create DB Namespace (user:password) for this cluster
    host: "ecample.com"
    port: "5432"
    user: "example"
    password: "example"
    # userQuota:  # < TODO: Add db quota reporting (disk usage)
    dbAdmin:  # < We expect an externally deployed DB cluster, put root access in here
      user: "postgres"
      password: "postgres"

  adminPassword: "default-admin-password"  # < It is what it seems to be

  # resourceQuotaSpec:  # < TODO: specify overall cluster quota (note: scale accordingly during multi-track deployment states, eg during migration)

  # nodeSelector:  # < Use for onsite, potentially air-gapped, deployments through node labels