apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/volumes/odoo-pv0001  # < ATTENTION: After *first* creation, ssh into the host and chmod 770 && chown root:2000; Note: 2000 is a magic group
    type: DirectoryOrCreate
